name = "NewtonMethods"
uuid = "3f801f47-33eb-4a39-a93c-698c5356c36d"
authors = ["Nicolas Brantut <nicolas.brantut@normalesup.org>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
